// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFBGIZeIIb6WYp4Z71Win5xIpEhZBGrc',
    appId: '1:1019552264881:web:cad1bd9dd490526fee6890',
    messagingSenderId: '1019552264881',
    projectId: 'skponline-5feb5',
    authDomain: 'skponline-5feb5.firebaseapp.com',
    storageBucket: 'skponline-5feb5.appspot.com',
    measurementId: 'G-BKVS6WPBNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3DVxBheHbSJFYYU1d2YbWql44nnao3Y',
    appId: '1:1019552264881:android:24807d8433b7b502ee6890',
    messagingSenderId: '1019552264881',
    projectId: 'skponline-5feb5',
    storageBucket: 'skponline-5feb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfI5P8iKp9gBocnOpJrJ6eqH3IsSMsNTw',
    appId: '1:1019552264881:ios:7d7a06c67f21010bee6890',
    messagingSenderId: '1019552264881',
    projectId: 'skponline-5feb5',
    storageBucket: 'skponline-5feb5.appspot.com',
    androidClientId: '1019552264881-plffq8v7hb7fpr9patrtnhd9d2f1ufm6.apps.googleusercontent.com',
    iosClientId: '1019552264881-81o0c4n3jrpp0mpl5rqv181v9chs6gmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfI5P8iKp9gBocnOpJrJ6eqH3IsSMsNTw',
    appId: '1:1019552264881:ios:7d7a06c67f21010bee6890',
    messagingSenderId: '1019552264881',
    projectId: 'skponline-5feb5',
    storageBucket: 'skponline-5feb5.appspot.com',
    androidClientId: '1019552264881-plffq8v7hb7fpr9patrtnhd9d2f1ufm6.apps.googleusercontent.com',
    iosClientId: '1019552264881-81o0c4n3jrpp0mpl5rqv181v9chs6gmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );
}
